deps.ts
dimで利用しているライブラリを最新版に更新いたしました。
但し、flatのみ0.0.15に問題があるとのことでしたので、0.0.14のまま更新しておりません。
=> Update library version to latest version

dim.ts, libs/actions.ts
Cliffyのバージョンアップに伴う型エラーの修正を行いました。
ご確認お願いいたします。
=> Changes description Cliffy version upgrade

README.md, libs/accessor.ts, libs/actions.ts, libs/types.ts
deno fmtを用いてフォーマットを整えましたので、ご確認ください
=> Use formatter

dim.ts, libs/accessor.ts, libs/actions.ts, libs/downloader.ts
=> Add header designation

libs/accessor.ts, libs/actions.ts, libs/consts.ts, libs/types.ts
管理情報ファイルのfileversion、未設定値の扱いを変更いたしました、ご確認ください。
=> Changes management information files

deps.ts, dim.ts, libs/actions.ts, libs/consts.ts, libs/types.ts
searchコマンドを実装しました。
ご確認お願いいたします。
#7
=> Add search command

libs/actions.ts
無効なURLを入力した場合にdim.jsonのみ書き込みが行われてしまう問題に対応いたしました。
=> Add handling install failures

README.md, dim.ts, libs/accessor.ts, libs/actions.ts, libs/downloader.ts
- install urlの重複制限を解除
- uninstall name で指定できるように変更
- update name で指定できるように変更
- 保存先ディレクトリの構造変更
上記4点の変更及び、READEMEを変更いたしましたのでご確認よろしくお願いいたします。
=> Remove url unique

deps.ts, libs/actions.ts, libs/downloader.ts
dawnload ライブラリを使用している処理を、ky を利用した処理に変更いたしました。
ご確認よろしくお願いいたします。
=> Change download to ky

deps.ts, libs/actions.ts, libs/downloader.ts, libs/types.ts
レスポンスヘッダーから情報を取得する処理を実装いたしましたのでご確認よろしくお願いいたします。
=> Get response headers

dim.ts, libs/actions.ts
dim-lock.json が存在する場合に、再ダウンロードが行われない問題への対応を行いましたのでご確認ください。
=> Allow redownloads on install

dim.ts, libs/accessor.ts, libs/actions.ts
installの-fオプションを追加し、-fオプションとURLを同時指定した場合にエラーを出力するようにいたしました。
=> Add -f option

libs/actions.ts
install 後処理指定方法を変更いたしましたのでご確認よろしくお願いいたします。
=> Change postProcessing arguments

libs/actions.ts
`installFromDimFile `内のヘッダーの設定値を修正いたしました。
ご確認お願いいたします。
=> Change headers setting values

README.md, libs/actions.ts, libs/types.ts
`lastDownloaded`のtypoを修正いたしました。
ご確認お願いいたします。
typo: `lastDonwloaded` → `lastDownloaded`
=> Fix lastDownloaded typo

README.md
READEM.mdにinstallコマンドの機能拡張に伴った変更を加えましたので、ご確認よろしくお願いいたします。
=> Update README to add install

libs/postprocess/xlsx_converter.ts
-pオプションのxlsx-to-csv使用時、ファイルの拡張子がcsvになるように変更いたしましたのでご確認ください。
=> Conversion from xlsx to csv

README.md
READMEにsearchコマンドと対話型検索オプションの説明を追加しました。
ご確認お願いいたします。
=> Update README to add search

README.md, doc/README.md
仕様説明書へのリンクをREADEME.mdに追加いたしました
=> Links to documents

libs/actions.ts, tests/libs/actions.list.test.ts, tests/libs/actions.search.test.ts, tests/test_data/searchData2.json
add tests which check if contents are null
* ListAction in actions.ts
* add test which  types "dim list" with catalogUrl, catalogResrceId, lastModified and eTag.
* SearchAction in actions.ts
* add searchData2.json
* add test which types "dim search "避難所" but xckan_description, license_title and resources(except for name and id) are null
=> add tests which check if contents are null
